### ISSUE TITLE
Request: Math Functionality

### ISSUE THREAD

**Issue by 16bitBlues** [Decicus/DecAPI#11]
I'm the user who emailed you last week just FYI. Thanks again for this useful tool. I was curious though if it would be possible to implement something like is available from [math.js](http://mathjs.org/)? Maybe not even that fully functional, but simple functions like addition/subtraction/multiplication/division and also the `&precision` option as well. If not, no worries!

**Comment by Decicus** [comment]
Thanks for the suggestion! Added it in https://github.com/Decicus/DecAPI/commit/23ab9b379e30a303dab2f273b99a57c6125aaac9.

Seems to be able to do the basic math operations that you requested, but nothing further than that.
You can test it here: `https://beta.decapi.me/math?exp=2%20*%2010`, remember to URL encode your `exp` parameter or else it might think `+` is a space character instead.

As for the `precision` option, I'm not sure what you mean. Mind clarifying?

**Comment by 16bitBlues** [comment]
Wow! Well that sure was fast. Thank you!

As for the `precision` option, on the math.js API it's basically their way of saying to "round up" a value. For example if you use it in the following link:

```http://api.mathjs.org/v1/?expr=9/2```
```http://api.mathjs.org/v1/?expr=9/2&precision=1```

You'll notice instead of giving "4.5" as the answer on the second URL, it rounds up to 5. It would be cool to have something like that. Even cooler if I could specify to round down or round up, but I'm not picky. Honestly just the `precision` or `rounding` would be great!

**Comment by Decicus** [comment]
Gotcha. I'll see what I can figure out. Seems I have to re-implement it anyways, as the library I use has a few issues that bother me.

For example, currently only the format `2 * 10` will work, but `2*10` will break (notice the lack of spaces in the latter example). I'll see what I can do.

**Comment by Decicus** [comment]
The new library I use seems to work a lot better. Added docs for it as well here: https://docs.decapi.me/#math_

Feel free to re-open if it doesn't work as you'd like.

**Comment by 16bitBlues** [comment]
Hey there! I seem to be running into some issues actually trying to execute it after cloning the latest repo changes (I decided to start from scratch again). The expression works fine on your site, but not on mine. It could just be something I did wrong or am missing, but basically I'm getting the following:

http://i.imgur.com/a9GyECu.png

```
FatalErrorException in MathController.php line 20:
syntax error, unexpected 'eval' (T_EVAL), expecting identifier (T_STRING)
```

Example URL (works fine on yours):
`https://beta.decapi.me/math?exp=9/2`

All other endpoints are still working without issue. Any ideas?

**Comment by Decicus** [comment]
What PHP version are you running?

Try pulling the newest version from the repo and see if it works now.

**Comment by 16bitBlues** [comment]
Yep that did it! Not sure why it wasn't working with `eval` but works with `evaluate`. I'm running `PHP 5.6.29` which [supports](http://php.net/manual/en/function.eval.php) that function. I also double checked my PHP configuration and verified the fuction wasn't disabled, and tested `eval(base64_decode...` with success. Weird. Either way, thanks for the quick fix!

**Comment by Decicus** [comment]
The problem didn't lie in the fact whether or not the PHP version supported `eval` as the documented function, but the fact I _named_ my function `eval`. Seems like PHP <7.0 doesn't like that.

**Comment by 16bitBlues** [comment]
Heyo! I didn't want to create an entirely new issue for this but I noticed a problem when attempting to add numbers. I think it's due to the `+` is not functioning as an expression but rather being seen as a parameter of the API if that makes any sense?

Example:
```
https://beta.decapi.me/math?exp=3+3
```

The above simply returns 3. Is there something I need to do extra to make addition work? Perhaps surround the `+` with a quotes or parentheses? When attempting a few things like that it seemed to have issues. Any help would be great!

**Comment by Decicus** [comment]
It's due to the way `+` is considered a "space" without URL encoding (as I mentioned in [this comment](https://github.com/Decicus/DecAPI/issues/11#issuecomment-272664377)). There's not really any good way to solve this other than URL encoding the `+` to `%2B`, e.g. `3%2B3` = `6`.

**Comment by 16bitBlues** [comment]
I completely missed your comment earlier somehow, my apologies. The URL encoding works just fine, thank you!
