### ISSUE TITLE
Feature Request: Team Member Results On One Line

### ISSUE THREAD

**Issue by dinosaw** [Decicus/DecAPI#12]
This is in reference to: http://docs.decapi.me/#twitch_team_members_TEAM_ID

Right now this returns the data in list format when requesting it in either JSON or text. However it would be great if it could be placed all on a single line, possibly with some separator such as a comma.

Example: `https://beta.decapi.me/twitch/team_members/nextlevel?text`
```
360chrism
fuzzyness
nospimi99
etc...
```

Instead:
```360chrism, fuzzyness, nospimi99```

**Comment by Decicus** [comment]
Thanks for the suggestion.

You can now add `implode` as a query parameter, and it will use whatever you specify in that parameter as the separator. With `implode` specified, you don't have to use `text` as the first implies the latter.

**Comment by dinosaw** [comment]
Working. Thanks!
