### ISSUE TITLE
Translations for output?

### ISSUE THREAD

**Issue by ronnicek** [Decicus/DecAPI#21]
Hi,

are you planning to have some translations? So output could be in different language then english?

**Comment by Decicus** [comment]
Hmm, not something I've thought much about, really, but it sounds like a good idea.

Anything specific endpoints you have in mind?

**Comment by ronnicek** [comment]
For example twitch followage (there is months and days) :)

**Comment by Decicus** [comment]
Oh, right. Good example.

This shouldn't be too hard to achieve, but I'll have to do some changes (e.g. upgrade the framework I use to a new version) in the code before I can pull it off.

Thanks for the suggestion :)

**Comment by ronnicek** [comment]
No rush at all.. :-) it will be just nice to have it

btw. thanks for great project!
