### ISSUE TITLE
DecAPI Twitch Auth Down? 502 Error

### ISSUE THREAD

**Issue by flatlin-e** [Decicus/DecAPI#24]
This seems to be down: [DecAPI Twitch Authenticator](https://decapi.me/auth/twitch?redirect=subcount&scopes=user_read+channel_subscriptions)

Really need this up as soon as possible to access clients' sub counts.

Thank you!

*503 Error rather

**Comment by Decicus** [comment]
It's an issue that I haven't been able to track down yet, as the errors seems to occur _somewhat randomly_ (meaning I haven't been able to reproduce it).  
The (current) workaround is to simply retry until it works.

Also, if you rely so heavily on the subscriber count I advise you to use the [`/kraken/channels/:channel_id/subscriptions` endpoint directly](https://dev.twitch.tv/docs/v5/reference/channels#get-channel-subscribers) yourself as you would no longer need to depend on DecAPI working to retrieve it.
