### ISSUE TITLE
Currency API not working

### ISSUE THREAD

**Issue by westor7** [Decicus/DecAPI#28]
Hello,

I love and i am using your currency api, but it seems not working now, it returns me an error.

Example URL: https://decapi.me/misc/currency?from=USD&to=EUR&value=50
Error: An error has occurred retrieving exchange rates

- Thanks!

**Comment by Decicus** [comment]
Seems the API I'm using did some backend changes. Shouldn't take long to fix.

**Comment by westor7** [comment]
Ok, please reply me when a fix applied.

- Thanks!

**Comment by Decicus** [comment]
Should be fixed now :)

**Comment by westor7** [comment]
Yes it fixed ! thanks!
