### ISSUE TITLE
izurvive API

### ISSUE THREAD

**Issue by ChrisYatesUK** [Decicus/DecAPI#79]
Hi, not an issue but couldn't find another way to make contact..
I'm trying to create an app that would make use of the chernarus map
Does izurvive have an API and if so where an I find more info ?
I came across your got repo from a google search..
if you could pop a message to mnoltdventures@gmail.com I can explain a bit more what I'm trying to achieve

Cheers

**Comment by Decicus** [comment]
There's some sort of API, but I'm pretty sure it's basically just versioned JSON files with coordinates.

Have you tried sending them an email? There are contact options at the bottom of this page: https://www.izurvive.com/about/
