### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by SrIzan10** [Decicus/DecAPI#88]
Hey! I do 5 Twitch requests every 2 minutes and it errors out with Too Many Requests.

These are the requests that I do:
https://decapi.me/twitch/uptime/
https://decapi.me/twitch/avatar/
https://decapi.me/twitch/viewercount/
https://decapi.me/twitch/title/
https://decapi.me/twitch/game/

**Comment by Decicus** [comment]
Change the `User-Agent` HTTP header to something else than the default. The default one used by `node-fetch` (or similar) has been blacklisted for the time being, due to abuse.

**Comment by SrIzan10** [comment]
thanks <3
